
SPRITE_SCALING = 0.5
SPRITE_NATIVE_SIZE = 128
SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * SPRITE_SCALING)

SCREEN_WIDTH = SPRITE_SIZE * 20
SCREEN_HEIGHT = SPRITE_SIZE * 15
SCREEN_TITLE = "Sprite Rooms Example"
USABLE_ROOM = SPRITE_SIZE + 10

SPRITE_SCALING_COIN = .125
SPRITE_SCALING_TEXT = .325
SPRITE_SCALING_TEXT2 = .350
COIN_COUNT = 50

MOVEMENT_SPEED = 5